# core/entities/exceptions.py
class UserNotFoundError(Exception):
    pass